name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install NPM Dependencies and Build Assets
        run: |
          npm install
          npm run production

      - name: Run Laravel Migrations
        run: php artisan migrate --force

      - name: Optimize Laravel Application
        run: php artisan optimize

      - name: Build
        run: php artisan build
