name: Laravel Testing with PostgreSQL
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install Composer dependencies
        run: composer install

      - name: Start PostgreSQL
        uses: docker://postgres:latest
        with:
          POSTGRES_DB: schedulelink
          POSTGRES_HOST_AUTH_METHOD: trust

          
      - name: Wait for PostgreSQL to start
        run: sleep 7
        
      - name: Create PostgreSQL database
        run: |
          psql -U postgres -c "CREATE DATABASE schedulelink;"
        env:
          POSTGRES_DB: schedulelink
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust

      - name: Run database migrations
        run: php artisan migrate

      - name: Start the application (use your actual start command)
        run: npm run dev & php artisan serve

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit
