name: Laravel Testing with PostgreSQL
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: schedulelink
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_USERNAME }}
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: NPM Install
      - run: npm ci
      - name: Debug Database Configuration
        run: |
          echo "DB_USERNAME: ${{ secrets.DB_USERNAME }}"
          echo "DB_PASSWORD: ${{ secrets.DB_USERNAME }}"
          pg_isready
      - name: Copy .env
        run: cp .env.example .env
      - name: Install Dependencies
        run: composer install --no-interaction --no-suggest
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Build Assets (Vite)
        run: npm install && npm run build
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
