name: Laravel Testing with PostgreSQL
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    env:
      DB_HOST: localhost
      DB_DATABASE: postgres
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install Composer dependencies
        run: composer install

      - name: Install dependencies
        run: npm ci

      - name: Copy .env File
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - name: Start the application (use your actual start command)
        run: npm run build

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit
